import { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  HiOutlineDocumentArrowDown,
  HiOutlineDocumentText,
  HiOutlineIdentification,
  HiOutlinePrinter,
  HiOutlineClipboardDocument,
  HiOutlineSparkles,
  HiOutlineCheckCircle,
  HiOutlineShieldCheck,
  HiOutlineExclamationTriangle,
} from 'react-icons/hi2';
import { Card, Badge, Button, Spinner } from '../../../components/common';
import auditService from '../../../services/audit.service';
import toast from 'react-hot-toast';

const fadeUp = {
  hidden: { opacity: 0, y: 14 },
  visible: (i = 0) => ({
    opacity: 1, y: 0,
    transition: { duration: 0.45, ease: [0.16, 1, 0.3, 1], delay: i * 0.06 },
  }),
};

const SEVERITY_LABEL = { low: 'Low Risk', medium: 'Medium Risk', high: 'High Risk', critical: 'Critical' };

const ReportsTab = ({ audit }) => {
  const [view, setView] = useState('menu');
  const [report, setReport] = useState(null);
  const [modelCard, setModelCard] = useState(null);
  const [loading, setLoading] = useState(false);
  const printRef = useRef(null);

  const handleGenerateReport = async () => {
    setLoading(true);
    setView('report');
    try {
      const res = await auditService.generateReport(audit._id);
      setReport(res.data.report);
    } catch (err) {
      toast.error('Failed to generate report');
      setView('menu');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateModelCard = async () => {
    setLoading(true);
    setView('modelcard');
    try {
      const res = await auditService.generateModelCard(audit._id);
      setModelCard(res.data.modelCard);
    } catch (err) {
      toast.error('Failed to generate model card');
      setView('menu');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = useCallback(() => {
    if (!printRef.current) return;
    const content = printRef.current.innerHTML;
    const win = window.open('', '_blank', 'width=900,height=700');
    win.document.write(`<!DOCTYPE html><html><head><title>FairScan Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a2e; line-height: 1.65; padding: 48px; max-width: 800px; margin: 0 auto; }
  h1 { font-size: 24px; font-weight: 700; margin-bottom: 8px; color: #0a0a1a; }
  h2 { font-size: 18px; font-weight: 600; margin: 32px 0 12px; color: #1a1a2e; border-bottom: 2px solid #e8e8f0; padding-bottom: 8px; }
  h3 { font-size: 15px; font-weight: 600; margin: 20px 0 8px; color: #2a2a4e; }
  p { margin-bottom: 12px; font-size: 14px; color: #3a3a5e; }
  .report-meta { font-size: 12px; color: #7a7a9e; margin-bottom: 32px; }
  .report-meta span { margin-right: 16px; }
  .severity-badge { display: inline-block; padding: 2px 10px; border-radius: 20px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
  .severity-low { background: #e8faf0; color: #0a8a5a; }
  .severity-medium { background: #fef8e8; color: #8a7a0a; }
  .severity-high { background: #fef0e8; color: #8a4a0a; }
  .severity-critical { background: #fee8e8; color: #8a1a1a; }
  .score-display { font-size: 36px; font-weight: 700; margin: 16px 0; }
  .mc-field { margin-bottom: 16px; }
  .mc-field label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; color: #7a7a9e; display: block; margin-bottom: 4px; }
  .mc-list { padding-left: 20px; margin-bottom: 12px; }
  .mc-list li { font-size: 14px; color: #3a3a5e; margin-bottom: 6px; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e8e8f0; font-size: 11px; color: #9a9abe; text-align: center; }
  @media print { body { padding: 24px; } }
</style></head><body>${content}
<div class="footer">Generated by FairScan — AI Fairness Auditing Platform · ${new Date().toLocaleDateString()}</div>
</body></html>`);
    win.document.close();
    setTimeout(() => win.print(), 400);
  }, []);

  const handleCopyJSON = useCallback((data) => {
    navigator.clipboard.writeText(JSON.stringify(data, null, 2));
    toast.success('Copied to clipboard');
  }, []);

  return (
    <div className="tab-reports">
      <AnimatePresence mode="wait">
        {/* ═══ Menu ═══ */}
        {view === 'menu' && (
          <motion.div
            key="menu"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.3 }}
          >
            {/* Quick info */}
            <motion.div custom={0} initial="hidden" animate="visible" variants={fadeUp}>
              <Card className="reports-intro">
                <HiOutlineDocumentArrowDown className="reports-intro__icon" />
                <div>
                  <h3>Export & Compliance Reports</h3>
                  <p>Generate enterprise-grade audit reports and model cards powered by Gemini AI. Reports are formatted for regulatory submission, legal review, and stakeholder communication.</p>
                </div>
              </Card>
            </motion.div>

            {/* Report cards */}
            <motion.div className="report-options" custom={1} initial="hidden" animate="visible" variants={fadeUp}>
              <Card hover className="report-option-card" onClick={handleGenerateReport}>
                <div className="report-option-card__icon" style={{ background: 'rgba(108, 92, 231, 0.12)', color: '#6C5CE7' }}>
                  <HiOutlineDocumentText />
                </div>
                <div className="report-option-card__body">
                  <h4>Full Audit Report</h4>
                  <p>Comprehensive bias audit report with executive summary, methodology, findings, regulatory mapping, and recommendations. Ready for legal and compliance teams.</p>
                  <div className="report-option-card__features">
                    <span><HiOutlineCheckCircle /> Executive Summary</span>
                    <span><HiOutlineCheckCircle /> Methodology</span>
                    <span><HiOutlineCheckCircle /> Findings & Recommendations</span>
                    <span><HiOutlineCheckCircle /> Compliance Assessment</span>
                  </div>
                </div>
                <Button variant="primary" size="sm">
                  Generate Report
                </Button>
              </Card>

              <Card hover className="report-option-card" onClick={handleGenerateModelCard}>
                <div className="report-option-card__icon" style={{ background: 'rgba(0, 214, 143, 0.12)', color: '#00D68F' }}>
                  <HiOutlineIdentification />
                </div>
                <div className="report-option-card__body">
                  <h4>Model Card</h4>
                  <p>Standardised model documentation following Google Model Cards best practices. Covers intended use, limitations, fairness metrics, and ethical considerations.</p>
                  <div className="report-option-card__features">
                    <span><HiOutlineCheckCircle /> Intended Use & Scope</span>
                    <span><HiOutlineCheckCircle /> Fairness Metrics</span>
                    <span><HiOutlineCheckCircle /> Ethical Considerations</span>
                    <span><HiOutlineCheckCircle /> Limitations & Recommendations</span>
                  </div>
                </div>
                <Button variant="primary" size="sm">
                  Generate Card
                </Button>
              </Card>
            </motion.div>
          </motion.div>
        )}

        {/* ═══ Full Report ═══ */}
        {view === 'report' && (
          <motion.div
            key="report"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.3 }}
          >
            <div className="report-toolbar">
              <Button variant="ghost" size="sm" onClick={() => setView('menu')}>
                ← Back to Reports
              </Button>
              {report && (
                <div className="report-toolbar__actions">
                  <Button variant="ghost" size="sm" icon={<HiOutlineClipboardDocument />} onClick={() => handleCopyJSON(report)}>
                    Copy JSON
                  </Button>
                  <Button variant="primary" size="sm" icon={<HiOutlinePrinter />} onClick={handlePrint}>
                    Export PDF
                  </Button>
                </div>
              )}
            </div>

            {loading ? (
              <Card>
                <div className="report-loading">
                  <Spinner size="md" />
                  <div>
                    <h4>Generating Audit Report</h4>
                    <p>Gemini is analyzing your audit data and composing a comprehensive report...</p>
                  </div>
                </div>
              </Card>
            ) : report ? (
              <Card className="report-preview" padding="none">
                <div className="report-document" ref={printRef}>
                  <div className="report-document__header">
                    <h1>{report.title || 'FairScan Bias Audit Report'}</h1>
                    <div className="report-meta">
                      <span>Dataset: {audit.datasetName}</span>
                      <span>Score: {audit.fairnessScore?.score}/100</span>
                      <span className={`severity-badge severity-${audit.severityScore}`}>
                        {SEVERITY_LABEL[audit.severityScore] || audit.severityScore}
                      </span>
                      <span>Generated: {new Date(report.generatedAt || Date.now()).toLocaleDateString()}</span>
                    </div>
                    <div className="score-display">{audit.fairnessScore?.score}<span style={{ fontSize: '18px', color: '#7a7a9e' }}>/100</span></div>
                  </div>

                  {(report.sections || []).map((section, i) => (
                    <div key={section.id || i} className="report-section">
                      <h2>{section.title}</h2>
                      {section.content.split('\n').map((para, pi) => (
                        para.trim() ? <p key={pi}>{para.trim()}</p> : null
                      ))}
                    </div>
                  ))}
                </div>
              </Card>
            ) : null}
          </motion.div>
        )}

        {/* ═══ Model Card ═══ */}
        {view === 'modelcard' && (
          <motion.div
            key="modelcard"
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.3 }}
          >
            <div className="report-toolbar">
              <Button variant="ghost" size="sm" onClick={() => setView('menu')}>
                ← Back to Reports
              </Button>
              {modelCard && (
                <div className="report-toolbar__actions">
                  <Button variant="ghost" size="sm" icon={<HiOutlineClipboardDocument />} onClick={() => handleCopyJSON(modelCard)}>
                    Copy JSON
                  </Button>
                  <Button variant="primary" size="sm" icon={<HiOutlinePrinter />} onClick={handlePrint}>
                    Export PDF
                  </Button>
                </div>
              )}
            </div>

            {loading ? (
              <Card>
                <div className="report-loading">
                  <Spinner size="md" />
                  <div>
                    <h4>Generating Model Card</h4>
                    <p>Gemini is building a standardised model card for your system...</p>
                  </div>
                </div>
              </Card>
            ) : modelCard ? (
              <Card className="report-preview" padding="none">
                <div className="report-document" ref={printRef}>
                  <div className="report-document__header">
                    <h1>{modelCard.modelName || 'Model Card'}</h1>
                    <div className="report-meta">
                      <span>Version: {modelCard.version}</span>
                      <span>Updated: {modelCard.lastUpdated ? new Date(modelCard.lastUpdated).toLocaleDateString() : 'N/A'}</span>
                      <span className={`severity-badge severity-${audit.severityScore}`}>
                        {SEVERITY_LABEL[audit.severityScore] || audit.severityScore}
                      </span>
                    </div>
                  </div>

                  {/* Intended Use */}
                  {modelCard.intendedUse && (
                    <div className="report-section">
                      <h2>Intended Use</h2>
                      <div className="mc-field"><label>Primary Use</label><p>{modelCard.intendedUse.primaryUse}</p></div>
                      <div className="mc-field"><label>Primary Users</label><p>{modelCard.intendedUse.primaryUsers}</p></div>
                      <div className="mc-field"><label>Out of Scope</label><p>{modelCard.intendedUse.outOfScope}</p></div>
                    </div>
                  )}

                  {/* Factors */}
                  {modelCard.factors && (
                    <div className="report-section">
                      <h2>Evaluation Factors</h2>
                      <div className="mc-field">
                        <label>Relevant Factors</label>
                        <ul className="mc-list">
                          {(modelCard.factors.relevantFactors || []).map((f, i) => <li key={i}>{f}</li>)}
                        </ul>
                      </div>
                      <div className="mc-field">
                        <label>Evaluation Metrics</label>
                        <ul className="mc-list">
                          {(modelCard.factors.evaluationFactors || []).map((f, i) => <li key={i}>{f}</li>)}
                        </ul>
                      </div>
                    </div>
                  )}

                  {/* Metrics */}
                  {modelCard.metrics && (
                    <div className="report-section">
                      <h2>Performance & Fairness Metrics</h2>
                      <div className="mc-metrics-grid">
                        <div className="mc-metric-card">
                          <span className="mc-metric-card__label">Fairness Score</span>
                          <span className="mc-metric-card__value">{modelCard.metrics.fairnessScore}/100</span>
                        </div>
                        <div className="mc-metric-card">
                          <span className="mc-metric-card__label">Severity</span>
                          <span className="mc-metric-card__value">{modelCard.metrics.severity}</span>
                        </div>
                      </div>
                      <div className="mc-field">
                        <label>Metrics Used</label>
                        <ul className="mc-list">
                          {(modelCard.metrics.metricsUsed || []).map((m, i) => <li key={i}>{m}</li>)}
                        </ul>
                      </div>
                    </div>
                  )}

                  {/* Ethical Considerations */}
                  {modelCard.ethicalConsiderations?.length > 0 && (
                    <div className="report-section">
                      <h2>Ethical Considerations</h2>
                      <ul className="mc-list">
                        {modelCard.ethicalConsiderations.map((e, i) => <li key={i}>{e}</li>)}
                      </ul>
                    </div>
                  )}

                  {/* Limitations */}
                  {modelCard.limitations?.length > 0 && (
                    <div className="report-section">
                      <h2>Known Limitations</h2>
                      <ul className="mc-list">
                        {modelCard.limitations.map((l, i) => <li key={i}>{l}</li>)}
                      </ul>
                    </div>
                  )}

                  {/* Recommendations */}
                  {modelCard.recommendations?.length > 0 && (
                    <div className="report-section">
                      <h2>Recommendations</h2>
                      <ul className="mc-list">
                        {modelCard.recommendations.map((r, i) => <li key={i}>{r}</li>)}
                      </ul>
                    </div>
                  )}

                  {/* Dataset Info */}
                  {modelCard.datasetInfo && (
                    <div className="report-section">
                      <h2>Dataset Information</h2>
                      <div className="mc-field"><label>Dataset Name</label><p>{modelCard.datasetInfo.name}</p></div>
                      <div className="mc-field"><label>Target Column</label><p>{modelCard.datasetInfo.targetColumn}</p></div>
                      <div className="mc-field">
                        <label>Protected Attributes</label>
                        <ul className="mc-list">
                          {(modelCard.datasetInfo.protectedAttributes || []).map((a, i) => <li key={i}>{a}</li>)}
                        </ul>
                      </div>
                    </div>
                  )}
                </div>
              </Card>
            ) : null}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default ReportsTab;
